// 会话标题的「自动占位」判定。
// 收尾后台只对仍是占位标题的会话自动生成标题（用户起过名的绝不覆盖）。
// 真源是 Session.titleAutoGenerated 标记（创建时声明、手动改名清除）；
// 该列上线前的存量会话没有标记，用占位格式兜底识别。

/** 历史占位标题（titleAutoGenerated 列上线前的两代默认值 + API 兜底值） */
const LEGACY_DEFAULT_TITLES = [
  '新建讲座会话',
  'New Lecture Session',
  'Untitled Session',
];

/**
 * 自动日期占位格式（NewSessionModal 生成）：
 *  zh: 「会话 7月12日 15:58」（zh-CN short 无前导零，兼容可能出现的 07月/AM 变体）
 *  en: 「Session Jul 12, 03:58 PM」（en-US short；也兼容 24 小时制环境无 AM/PM 的输出）
 */
const AUTO_TITLE_PATTERNS = [
  /^会话 \d{1,2}月\d{1,2}日 \d{1,2}:\d{2}(?:\s?[AP]M)?$/,
  /^Session [A-Za-z]{3,9} \d{1,2}, \d{1,2}:\d{2}(?:\s?[AP]M)?$/,
];

/**
 * 该会话标题是否仍是系统自动生成的占位。
 * @param title 当前标题
 * @param titleAutoGenerated Session 行上的显式标记（新数据的真源）
 */
export function isAutoGeneratedSessionTitle(
  title: string,
  titleAutoGenerated?: boolean | null
): boolean {
  if (titleAutoGenerated) return true;
  const trimmed = title.trim();
  if (LEGACY_DEFAULT_TITLES.includes(trimmed)) return true;
  return AUTO_TITLE_PATTERNS.some((re) => re.test(trimmed));
}
