import type { Locale } from '@/lib/i18n';

/**
 * 落地页文案（中英双语）。语言由 useI18n() 的 locale 决定：
 * 已存偏好 → 浏览器语言 → 站点默认。UI 语言切换与全站一致。
 * ${siteName} 与 {param} 占位符在 makeLandingCopy 里替换。
 */
const dict: Record<Locale, Record<string, string>> = {
  zh: {
    "bento.ai.h3": "模型可以换，课堂上下文不会丢。",
    "bento.ai.p": "接入 Claude、GPT、DeepSeek 或任意 OpenAI 兼容服务，用同一份课堂材料继续总结、报告与问答。",
    "bento.ai.topline": "多模型 AI",
    "bento.export.h3": "不是困在产品里的笔记。",
    "bento.export.p": "按学习、字幕与归档场景，导出常见格式。",
    "bento.export.topline": "随时带走",
    "bento.ownership.h3": "应用和存储，留在你掌控的系统里。",
    "bento.ownership.p": "通过 Docker Compose 部署完整服务栈；语音识别、LLM 与文件存储供应商由管理员按需配置，凭据加密保存。",
    "bento.ownership.topline": "自托管",
    "bento.playback.h3": "听到哪里，文字就亮到哪里。",
    "bento.playback.p": "音频与转录保持关联，复盘时直接回到当时的上下文。",
    "bento.playback.topline": "同步回放",
    "bento.playback.visual.line1": "光合作用首先需要捕获来自太阳的能量。",
    "bento.playback.visual.line2": "叶绿素分子在这里扮演了核心角色。",
    "bento.playback.visual.line3": "这些能量随后会被暂时储存在 ATP 中。",
    "bento.translation.h3": "云端速度，或本地隐私。",
    "bento.translation.miniTranslation.result": "能量被转换。",
    "bento.translation.p": "按场景选择 Soniox 云端翻译，或通过 WebGPU 在浏览器里运行本地 ONNX 模型。",
    "bento.translation.topline": "灵活翻译",
    "capabilities.h2": "下课以后，知识没有散场。",
    "capabilities.kicker": "AFTER THE BELL",
    "capabilities.p": "录音、逐字稿、译文、摘要、关键词与问答始终围绕同一场课堂组织。复习不再是重新拼凑，而是从任何一个线索继续。",
    "continuum.header.h3": "一份课堂记录，通往每一种下一步。",
    "continuum.header.kicker": "ONE SOURCE · MANY WAYS FORWARD",
    "continuum.node.0": "声音",
    "continuum.node.1": "逐字稿",
    "continuum.node.2": "译文",
    "continuum.node.3": "摘要",
    "continuum.node.4": "问答",
    "continuum.node.5": "分享",
    "cta.enter": "进入 LectureLive",
    "cta.start": "开始记录",
    "cta.workspace": "进入工作区",
    "finalCta.h2": "下一堂课，别再从一页空白开始。",
    "finalCta.kicker": "YOUR NEXT LECTURE STARTS HERE",
    "finalCta.login": "已有账号，直接登录",
    "finalCta.orbit.0": "实时字幕",
    "finalCta.orbit.1": "AI 总结",
    "finalCta.orbit.2": "同步分享",
    "finalCta.p": "打开麦克风，让课堂从第一句话起就成为可以回放、理解、分享和继续思考的知识。",
    "footer.copyright": "Open-source & self-hosted.",
    "footer.links.login": "登录",
    "footer.links.privacy": "隐私",
    "footer.links.terms": "条款",
    "footer.tagline": "让每一堂课，都有回声。",
    "hero.aiBadge.sub": "3 个新要点",
    "hero.aiBadge.title": "AI 摘要已更新",
    "hero.description": "实时转录、多语言翻译、AI 总结与分享，串成一条不打断思考的学习流。你只管专心听，知识自己会留下来。",
    "hero.eyebrow": "REAL-TIME LEARNING OS",
    "hero.floatBadge.language": "中文",
    "hero.h1.accent": "每一句话，",
    "hero.h1.lead": "让课堂里的",
    "hero.h1.tail": "继续生长。",
    "hero.scrollCue.aria": "继续向下浏览",
    "hero.secondaryCta": "看它怎么工作",
    "hero.signals.0": "实时字幕",
    "hero.signals.1": "多语言",
    "hero.signals.2": "可回放",
    "hero.window.pauseButton.aria": "暂停录音",
    "hero.window.transcript.active.label": "正在识别",
    "hero.window.transcript.zhLine": "光合作用是植物将光能转化为化学能的过程。",
    "hero.window.transcript.zhLine.label": "实时译文",
    "nav.aria": "首页导航",
    "nav.brand.aria": "${siteName} 首页",
    "nav.capabilities": "能力",
    "nav.login": "登录",
    "nav.ownership": "自托管",
    "nav.workflow": "工作流",
    "scene.capture.activeRow.label": "正在识别",
    "scene.capture.activeRow.text": "接下来，我们来看这个过程如何影响……",
    "scene.capture.row1": "光合作用把光能转换成细胞可以储存的化学能。",
    "scene.capture.row2": "所以第一阶段发生在叶绿体的类囊体膜上。",
    "scene.capture.toolbarMeta": "信号清晰",
    "scene.share.audience.count": "12 人正在同步",
    "scene.share.audience.sub": "正在接收最新字幕",
    "scene.share.copyButton": "复制",
    "scene.share.hero.eyebrow": "LIVE CLASSROOM",
    "scene.share.hero.p": "学生无需进入编辑工作区，也能同步查看转录、译文和课堂重点。",
    "scene.think.answer": "她把 ATP 比作“随取随用的能量零钱”，并与长期储能分子作了对比。",
    "scene.think.header.status": "已生成",
    "scene.think.header.sub": "基于 42 分钟完整转录",
    "scene.think.header.title": "课堂智能摘要",
    "scene.think.question": "老师刚才对 ATP 的作用做了什么类比？",
    "scene.think.summaryCard.label": "核心概念",
    "scene.think.summaryCard.li1": "光能由叶绿素吸收并驱动电子传递",
    "scene.think.summaryCard.li2": "ATP 与 NADPH 为后续反应提供能量",
    "scene.think.summaryCard.li3": "氧气作为水分解的副产物释放",
    "scene.think.summaryCard.title": "光反应如何完成能量转换",
    "scene.translate.langHeader.zh": "简体中文",
    "scene.translate.localBadge": "本地翻译可用",
    "scene.translate.pane.accent.label": "译文",
    "scene.translate.pane.accent.line1": "能量并没有在这个过程中被创造，而是被转换并储存下来。",
    "scene.translate.pane.accent.line2": "叶绿素分子在捕获光能的过程中起到核心作用。",
    "skipLink": "跳到主要内容",
    "story.h2": "从开口，到真正掌握。",
    "story.kicker": "ONE CONTINUOUS FLOW",
    "story.navButton.aria": "跳到步骤 {index}：{label}",
    "storyStep.0.description": "浏览器直连流式语音识别，老师话音未落，文字已经成形——结构清晰、逐句生长的课堂记录。",
    "storyStep.0.label": "CAPTURE",
    "storyStep.0.title": "声音落下，文字同时生长。",
    "storyStep.1.description": "原文与译文沿着同一条时间线并肩出现。云端翻译与浏览器本地翻译皆可接入，让双语课堂始终同步。",
    "storyStep.1.label": "TRANSLATE",
    "storyStep.1.title": "不必等到下课，才开始理解。",
    "storyStep.2.description": "从完整转录生成摘要、关键词、结构化报告，并围绕课堂内容继续提问。支持多家 LLM 与自定义模型。",
    "storyStep.2.label": "THINK",
    "storyStep.2.title": "把一小时，折叠成真正有用的重点。",
    "storyStep.3.description": "通过直播链接同步给学生，课后继续回放、复盘与导出。声音、文字与理解，始终留在一起。",
    "storyStep.3.label": "SHARE",
    "storyStep.3.title": "同一堂课，所有人都在现场。",
    "wordStream.0": "听见",
    "wordStream.1": "理解",
    "wordStream.2": "记住",
    "wordStream.3": "分享",
  },
  en: {
    "bento.ai.h3": "Swap the model; the class context stays.",
    "bento.ai.p": "Connect Claude, GPT, DeepSeek, or any OpenAI-compatible service, and keep summarizing, reporting, and asking questions over the same class material.",
    "bento.ai.topline": "Multi-model AI",
    "bento.export.h3": "Notes that aren't trapped inside the product.",
    "bento.export.p": "Export to common formats for studying, subtitles, and archiving.",
    "bento.export.topline": "Take it anywhere",
    "bento.ownership.h3": "The app and its storage stay on systems you control.",
    "bento.ownership.p": "Deploy the full stack with Docker Compose. Admins configure the speech recognition, LLM, and file-storage providers as needed, with credentials stored encrypted.",
    "bento.ownership.topline": "Self-hosted",
    "bento.playback.h3": "Wherever you're listening, the words light up.",
    "bento.playback.p": "Audio and transcript stay linked, so reviewing drops you right back into the moment.",
    "bento.playback.topline": "Synced replay",
    "bento.playback.visual.line1": "Photosynthesis first has to capture energy from the sun.",
    "bento.playback.visual.line2": "The chlorophyll molecule plays the central role here.",
    "bento.playback.visual.line3": "That energy is then stored, briefly, in ATP.",
    "bento.translation.h3": "Cloud speed, or local privacy.",
    "bento.translation.miniTranslation.result": "Energy is transformed.",
    "bento.translation.p": "Choose Soniox cloud translation for the moment, or run a local ONNX model right in the browser via WebGPU.",
    "bento.translation.topline": "Flexible translation",
    "capabilities.h2": "After the bell, the knowledge doesn't clear out.",
    "capabilities.kicker": "AFTER THE BELL",
    "capabilities.p": "Recording, transcript, translation, summary, keywords, and Q&A all stay organized around the same class. Reviewing is no longer piecing it back together — it's picking up from any thread.",
    "continuum.header.h3": "One class record, a path to every next step.",
    "continuum.header.kicker": "ONE SOURCE · MANY WAYS FORWARD",
    "continuum.node.0": "Voice",
    "continuum.node.1": "Transcript",
    "continuum.node.2": "Translation",
    "continuum.node.3": "Summary",
    "continuum.node.4": "Q&A",
    "continuum.node.5": "Share",
    "cta.enter": "Enter LectureLive",
    "cta.start": "Start recording",
    "cta.workspace": "Open workspace",
    "finalCta.h2": "Your next class shouldn't start from a blank page.",
    "finalCta.kicker": "YOUR NEXT LECTURE STARTS HERE",
    "finalCta.login": "Already have an account? Log in",
    "finalCta.orbit.0": "Live captions",
    "finalCta.orbit.1": "AI summaries",
    "finalCta.orbit.2": "Synced sharing",
    "finalCta.p": "Turn on the mic, and from its very first word your class becomes knowledge you can replay, understand, share, and keep thinking about.",
    "footer.copyright": "Open-source & self-hosted.",
    "footer.links.login": "Log in",
    "footer.links.privacy": "Privacy",
    "footer.links.terms": "Terms",
    "footer.tagline": "Let every class leave an echo.",
    "hero.aiBadge.sub": "3 new points",
    "hero.aiBadge.title": "AI summary updated",
    "hero.description": "Real-time transcription, multilingual translation, AI summaries and sharing — strung into one learning flow that never interrupts your thinking. Just listen; the knowledge stays behind on its own.",
    "hero.eyebrow": "REAL-TIME LEARNING OS",
    "hero.floatBadge.language": "Chinese",
    "hero.h1.accent": "keep growing.",
    "hero.h1.lead": "Let every word",
    "hero.h1.tail": "",
    "hero.scrollCue.aria": "Keep scrolling",
    "hero.secondaryCta": "See how it works",
    "hero.signals.0": "Live captions",
    "hero.signals.1": "Multilingual",
    "hero.signals.2": "Replayable",
    "hero.window.pauseButton.aria": "Pause recording",
    "hero.window.transcript.active.label": "Transcribing…",
    "hero.window.transcript.zhLine": "Photosynthesis is how plants turn light energy into chemical energy.",
    "hero.window.transcript.zhLine.label": "Live translation",
    "nav.aria": "Home navigation",
    "nav.brand.aria": "${siteName} home",
    "nav.capabilities": "Capabilities",
    "nav.login": "Log in",
    "nav.ownership": "Self-hosted",
    "nav.workflow": "Workflow",
    "scene.capture.activeRow.label": "Transcribing",
    "scene.capture.activeRow.text": "Next, let's look at how this process affects…",
    "scene.capture.row1": "Photosynthesis converts light energy into chemical energy the cell can store.",
    "scene.capture.row2": "So the first stage happens on the thylakoid membrane of the chloroplast.",
    "scene.capture.toolbarMeta": "Signal clear",
    "scene.share.audience.count": "12 people in sync",
    "scene.share.audience.sub": "Receiving the latest captions",
    "scene.share.copyButton": "Copy",
    "scene.share.hero.eyebrow": "LIVE CLASSROOM",
    "scene.share.hero.p": "Students follow the transcript, translation, and key points in sync — no editing workspace needed.",
    "scene.think.answer": "She compared ATP to “energy small change you can spend on demand,” contrasting it with long-term storage molecules.",
    "scene.think.header.status": "Generated",
    "scene.think.header.sub": "From the full 42-minute transcript",
    "scene.think.header.title": "Smart class summary",
    "scene.think.question": "What analogy did the teacher just use for ATP's role?",
    "scene.think.summaryCard.label": "Core concept",
    "scene.think.summaryCard.li1": "Chlorophyll absorbs light energy and drives electron transfer",
    "scene.think.summaryCard.li2": "ATP and NADPH power the reactions that follow",
    "scene.think.summaryCard.li3": "Oxygen is released as a by-product of splitting water",
    "scene.think.summaryCard.title": "How the light reactions carry out energy conversion",
    "scene.translate.langHeader.zh": "Simplified Chinese",
    "scene.translate.localBadge": "Local translation available",
    "scene.translate.pane.accent.label": "Translation",
    "scene.translate.pane.accent.line1": "Energy isn't created in this process — it's transformed and stored.",
    "scene.translate.pane.accent.line2": "The chlorophyll molecule plays a central role in capturing light energy.",
    "skipLink": "Skip to main content",
    "story.h2": "From the first word to real mastery.",
    "story.kicker": "ONE CONTINUOUS FLOW",
    "story.navButton.aria": "Jump to step {index}: {label}",
    "storyStep.0.description": "The browser streams straight to speech recognition — before the teacher finishes speaking, the words have taken shape. A clean, line-by-line record that grows as class unfolds.",
    "storyStep.0.label": "CAPTURE",
    "storyStep.0.title": "As the voice lands, the words grow with it.",
    "storyStep.1.description": "Source and translation appear side by side on one timeline. Plug in cloud translation or in-browser local translation to keep a bilingual classroom always in sync.",
    "storyStep.1.label": "TRANSLATE",
    "storyStep.1.title": "Understanding shouldn't wait for the bell.",
    "storyStep.2.description": "Generate summaries, keywords, and structured reports from the full transcript — then keep asking questions about what was taught. Works with multiple LLMs and your own custom models.",
    "storyStep.2.label": "THINK",
    "storyStep.2.title": "Fold an hour into the points that actually matter.",
    "storyStep.3.description": "Share a live link with students, then replay, review, and export long after class. Voice, text, and understanding always stay together.",
    "storyStep.3.label": "SHARE",
    "storyStep.3.title": "One class, and everyone's in the room.",
    "wordStream.0": "Hear",
    "wordStream.1": "Understand",
    "wordStream.2": "Remember",
    "wordStream.3": "Share",
  },
};

export type LandingT = (key: string, params?: Record<string, string | number>) => string;

export function makeLandingCopy(locale: Locale, siteName: string): LandingT {
  const table = dict[locale] ?? dict.en;
  return (key, params) => {
    let value = table[key] ?? dict.en[key] ?? key;
    value = value.replace(/\$\{siteName\}/g, siteName);
    if (params) {
      value = value.replace(/\{(\w+)\}/g, (_, p) =>
        params[p] !== undefined ? String(params[p]) : `{${p}}`
      );
    }
    return value;
  };
}
