/**
 * Soniox Client Wrapper
 *
 * Wraps the @soniox/client SDK for real-time speech-to-text.
 * Uses the Direct Stream approach: browser connects directly to Soniox WebSocket
 * via a temporary API key generated by our backend.
 */

import type { SonioxSessionConfig } from '@/types/soniox';
import type {
  SessionConfig,
  AudioSourceType,
  SonioxRegionPreference,
} from '@/types/transcript';
import type { TemporaryApiKeyResponse } from '@/types/soniox';
import { BrowserAudioInputSource } from '@/lib/audio/browserAudioInputSource';
import { resolveAutoRegion } from '@/lib/soniox/clientPing';

export function buildSonioxConfig(config: SessionConfig): SonioxSessionConfig {
  const sonioxConfig: SonioxSessionConfig = {
    model: config.model,
    language_hints: config.languageHints,
    enable_speaker_diarization: config.enableSpeakerDiarization,
    enable_language_identification: config.enableLanguageIdentification,
    enable_endpoint_detection: config.enableEndpointDetection,
    max_endpoint_delay_ms: config.endpointDetectionMs,
  };

  // Add domain context if provided
  if (config.domain || config.topic || config.terms.length > 0) {
    const generalContext: Array<{ key: string; value: string }> = [];
    sonioxConfig.context = {
      general: generalContext,
      terms: config.terms.length > 0 ? config.terms : undefined,
    };
    if (config.domain) {
      generalContext.push({ key: 'domain', value: config.domain });
    }
    if (config.topic) {
      generalContext.push({ key: 'topic', value: config.topic });
    }
  }

  // Add translation config if target language is specified
  if (config.targetLang && config.translationMode !== 'local') {
    if (config.twoWayTranslation) {
      // 来回翻译模式：双向翻译
      sonioxConfig.translation = {
        type: 'two_way',
        language_a: config.sourceLang,
        language_b: config.targetLang,
      };
    } else {
      sonioxConfig.translation = {
        type: 'one_way',
        target_language: config.targetLang,
      };
    }
  }

  return sonioxConfig;
}

export async function fetchTemporaryApiKey(
  authToken: string,
  regionPreference?: SonioxRegionPreference
): Promise<TemporaryApiKeyResponse> {
  // auto 模式下，用客户端 ping 选延迟最低的区域
  let resolvedRegion: string | undefined;
  if (!regionPreference || regionPreference === 'auto') {
    const best = await resolveAutoRegion();
    if (best) {
      resolvedRegion = best;
    }
  } else {
    resolvedRegion = regionPreference;
  }

  const res = await fetch('/api/soniox/temporary-key', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      region: resolvedRegion,
    }),
  });
  if (!res.ok) {
    const errorBody = await res.json().catch(() => ({})) as { error?: string };
    throw new Error(errorBody.error || 'Failed to get temporary API key');
  }
  const data = await res.json();
  return data as TemporaryApiKeyResponse;
}

/**
 * Initialize the Soniox real-time recording session.
 *
 * This function dynamically imports @soniox/client to keep it client-side only.
 * Returns the recording handle and client instance.
 */
export async function startSonioxRecording(
  config: SonioxSessionConfig,
  authToken: string,
  callbacks: {
    onPartialResult: (tokens: unknown[]) => void;
    onEndpoint: () => void;
    onError: (error: Error) => void;
    onConnectionChange: (state: string) => void;
  },
  options?: {
    sourceType?: AudioSourceType;
    deviceId?: string | null;
    preAcquiredStream?: MediaStream | null;
    managedStream?: MediaStream | null;
    regionPreference?: SonioxRegionPreference;
    onAudioLevel?: (level: number) => void;
  }
) {
  // Dynamic import to ensure client-side only
  const { SonioxClient, BrowserPermissionResolver } = await import('@soniox/client');

  callbacks.onConnectionChange('connecting');
  const temporaryKey = await fetchTemporaryApiKey(
    authToken,
    options?.regionPreference
  );
  const wsBaseUrl = temporaryKey.ws_url ?? temporaryKey.ws_base_url;
  if (!wsBaseUrl) {
    throw new Error('Soniox temporary key response missing ws_url');
  }

  const client = new SonioxClient({
    api_key: temporaryKey.api_key,
    ws_base_url: wsBaseUrl,
    permissions: new BrowserPermissionResolver(),
  });

  try {
      const source = new BrowserAudioInputSource({
        sourceType: options?.sourceType ?? 'mic',
        deviceId: options?.deviceId,
        preAcquiredStream: options?.preAcquiredStream,
        managedStream: options?.managedStream,
        onAudioLevel: options?.onAudioLevel,
      });

    const recording = client.realtime.record({
      ...config,
      source,
    });

    recording.on('connected', () => {
      callbacks.onConnectionChange('connected');
    });

    recording.on('result', (result: { tokens: unknown[] }) => {
      callbacks.onPartialResult(result.tokens);
    });

    recording.on('endpoint', () => {
      callbacks.onEndpoint();
    });

    recording.on('error', (error: Error) => {
      callbacks.onConnectionChange('error');
      callbacks.onError(error);
    });

    return {
      recording,
      client,
      source,
      temporaryKey: {
        ...temporaryKey,
        ws_base_url: wsBaseUrl,
      },
    };
  } catch (error) {
    callbacks.onConnectionChange('error');
    throw error;
  }
}
