/**
 * Soniox Client Wrapper
 *
 * Wraps the @soniox/client SDK for real-time speech-to-text.
 * Uses the Direct Stream approach: browser connects directly to Soniox WebSocket
 * via a temporary API key generated by our backend.
 */

import type { SonioxSessionConfig } from '@/types/soniox';
import type {
  SessionConfig,
  AudioSourceType,
  SonioxRegionPreference,
} from '@/types/transcript';
import type { TemporaryApiKeyResponse } from '@/types/soniox';
import { BrowserAudioInputSource } from '@/lib/audio/browserAudioInputSource';
import { resolveAutoRegion } from '@/lib/soniox/clientPing';

const SONIOX_MIN_ENDPOINT_DELAY_MS = 500;
const SONIOX_MAX_ENDPOINT_DELAY_MS = 3000;
const SONIOX_DEFAULT_ENDPOINT_DELAY_MS = 2000;

function clampEndpointDelayMs(value?: number): number | undefined {
  if (!Number.isFinite(value)) {
    return undefined;
  }

  return Math.min(
    SONIOX_MAX_ENDPOINT_DELAY_MS,
    Math.max(SONIOX_MIN_ENDPOINT_DELAY_MS, Math.round(value as number))
  );
}

function deriveLanguageHints(config: SessionConfig): {
  hints: string[] | undefined;
  strict: boolean | undefined;
} {
  const normalized = Array.from(
    new Set(
      (
        config.twoWayTranslation
          ? [config.sourceLang, config.targetLang]
          : [config.sourceLang]
      )
        .map((lang) => lang?.trim().toLowerCase())
        .filter(Boolean)
    )
  );

  if (normalized.length > 0) {
    return {
      hints: normalized,
      strict:
        config.languageHintsStrict ??
        (normalized.length === 1 && !config.twoWayTranslation ? true : undefined),
    };
  }

  return {
    hints: config.languageHints.length > 0 ? config.languageHints : undefined,
    strict: config.languageHintsStrict,
  };
}

export function buildSonioxConfig(config: SessionConfig): SonioxSessionConfig {
  const endpointDelayMs =
    clampEndpointDelayMs(config.endpointDetectionMs) ?? SONIOX_DEFAULT_ENDPOINT_DELAY_MS;
  const { hints: languageHints, strict: languageHintsStrict } =
    deriveLanguageHints(config);

  const sonioxConfig: SonioxSessionConfig = {
    model: config.model,
    language_hints: languageHints,
    language_hints_strict: languageHintsStrict,
    enable_speaker_diarization: config.enableSpeakerDiarization,
    enable_language_identification: config.enableLanguageIdentification,
    enable_endpoint_detection: config.enableEndpointDetection,
    max_endpoint_delay_ms: endpointDelayMs,
    client_reference_id: config.clientReferenceId,
  };

  // Add domain context if provided
  if (config.domain || config.topic || config.terms.length > 0) {
    const generalContext: Array<{ key: string; value: string }> = [];
    sonioxConfig.context = {
      general: generalContext,
      terms: config.terms.length > 0 ? config.terms : undefined,
    };
    if (config.domain) {
      generalContext.push({ key: 'domain', value: config.domain });
    }
    if (config.topic) {
      generalContext.push({ key: 'topic', value: config.topic });
    }
  }

  // Add translation config only in pure cloud mode.
  // 'local' 走浏览器内置模型，'both' 也由本地引擎产出译文（见 useTranslation）——
  // 这两种模式下都不能再发 Soniox 云翻译，否则云/本地译文写同一个 translations[segId]
  // 互相覆盖（对比失效），且 'both' 会平白翻倍 Soniox 翻译成本。
  if (config.targetLang && config.translationMode === 'soniox') {
    if (config.terms.length > 0) {
      sonioxConfig.context = {
        ...sonioxConfig.context,
        translation_terms: config.terms.map((term) => ({
          source: term,
          target: term,
        })),
      };
    }

    if (config.twoWayTranslation) {
      // 来回翻译模式：双向翻译
      sonioxConfig.translation = {
        type: 'two_way',
        language_a: config.sourceLang,
        language_b: config.targetLang,
      };
    } else {
      sonioxConfig.translation = {
        type: 'one_way',
        target_language: config.targetLang,
      };
    }
  }

  return sonioxConfig;
}

/**
 * R1-L1：mint 时的流归属声明。服务端据此做预扣门禁并把 grant 关联到可结算实体
 * （realtime → Session finalize 链；interpret → InterpretSession deduct/cron 链），
 * 并以之构造 Soniox 侧的 client_reference_id（服务端拼 kind:userId:grantId，客户端不可控）。
 */
export interface StreamAttribution {
  kind: 'realtime' | 'interpret';
  /** realtime 必填：所属 Session.id（服务端校验归属+活跃状态）。 */
  sessionId?: string;
  /** interpret 可选：/interpret/start 返回的 anchorId（精确关联，多标签页并发不串场）。 */
  anchorId?: string | null;
}

export async function fetchTemporaryApiKey(
  authToken: string,
  regionPreference?: SonioxRegionPreference,
  attribution?: StreamAttribution
): Promise<TemporaryApiKeyResponse> {
  // auto 模式下，用客户端 ping 选延迟最低的区域
  let resolvedRegion: string | undefined;
  if (!regionPreference || regionPreference === 'auto') {
    const best = await resolveAutoRegion();
    if (best) {
      resolvedRegion = best;
    }
  } else {
    resolvedRegion = regionPreference;
  }

  const res = await fetch('/api/soniox/temporary-key', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      region: resolvedRegion,
      kind: attribution?.kind,
      sessionId: attribution?.sessionId,
      anchorId: attribution?.anchorId ?? undefined,
    }),
  });
  if (!res.ok) {
    const errorBody = await res.json().catch(() => ({})) as { error?: string };
    throw new Error(errorBody.error || 'Failed to get temporary API key');
  }
  const data = await res.json();
  return data as TemporaryApiKeyResponse;
}

/**
 * Initialize the Soniox real-time recording session.
 *
 * This function dynamically imports @soniox/client to keep it client-side only.
 * Returns the recording handle and client instance.
 */
export async function startSonioxRecording(
  config: SonioxSessionConfig,
  authToken: string,
  callbacks: {
    onPartialResult: (tokens: unknown[]) => void;
    onEndpoint: () => void;
    onError: (error: Error) => void;
    onConnectionChange: (state: string) => void;
  },
  options?: {
    sourceType?: AudioSourceType;
    deviceId?: string | null;
    preAcquiredStream?: MediaStream | null;
    managedStream?: MediaStream | null;
    regionPreference?: SonioxRegionPreference;
    attribution?: StreamAttribution;
    onAudioLevel?: (level: number) => void;
  }
) {
  // ── E2E 测试接缝 ──
  // 真实 Soniox SDK 需要连 wss://stt-rt.soniox.com，无法在 e2e 环境运行。当页面显式设置
  // window.__E2E_FAKE_SONIOX__ 时（仅测试注入，生产永不置位），返回一个假转录连接，并把
  // 驱动接口挂到 window.__sonioxTest 供 e2e 触发「连上 / 断网 / 收到 token」，从而端到端验证
  // 录音态与断网续采等整页行为。仍复用真实 archiveManager（配合 chromium 假麦克风真录音频）。
  if (typeof window !== 'undefined' && (window as unknown as Record<string, unknown>).__E2E_FAKE_SONIOX__) {
    callbacks.onConnectionChange('connecting');
    const fakeRecording = {
      stop: async () => {},
      pause: () => {},
      resume: () => {},
      on: () => {},
    };
    (window as unknown as Record<string, unknown>).__sonioxTest = {
      connect: () => callbacks.onConnectionChange('connected'),
      error: (msg?: string) => {
        callbacks.onConnectionChange('error');
        callbacks.onError(new Error(msg ?? 'e2e disconnect'));
      },
      token: (tokens: unknown[]) => callbacks.onPartialResult(tokens),
      endpoint: () => callbacks.onEndpoint(),
    };
    // 不自动连上：连接/断网/token 全部由 e2e 通过 __sonioxTest 显式驱动，避免重连自动连上
    // 把「转录中断」提示覆盖掉，测试可精确控制时序。
    return {
      recording: fakeRecording,
      client: {},
      source: {},
      temporaryKey: {
        region: 'test',
        ws_base_url: 'wss://fake',
        api_key: 'fake',
        expires_at: '',
      } as unknown as TemporaryApiKeyResponse,
    };
  }

  // Dynamic import to ensure client-side only
  const { SonioxClient, BrowserPermissionResolver } = await import('@soniox/client');

  callbacks.onConnectionChange('connecting');
  const temporaryKey = await fetchTemporaryApiKey(
    authToken,
    options?.regionPreference,
    options?.attribution
  );
  const wsBaseUrl = temporaryKey.ws_url ?? temporaryKey.ws_base_url;
  if (!wsBaseUrl) {
    throw new Error('Soniox temporary key response missing ws_url');
  }

  const client = new SonioxClient({
    api_key: temporaryKey.api_key,
    ws_base_url: wsBaseUrl,
    permissions: new BrowserPermissionResolver(),
  });

  try {
      const source = new BrowserAudioInputSource({
        sourceType: options?.sourceType ?? 'mic',
        deviceId: options?.deviceId,
        preAcquiredStream: options?.preAcquiredStream,
        managedStream: options?.managedStream,
        onAudioLevel: options?.onAudioLevel,
      });

    const recording = client.realtime.record({
      ...config,
      source,
    });

    recording.on('connected', () => {
      callbacks.onConnectionChange('connected');
    });

    recording.on('result', (result: { tokens: unknown[] }) => {
      callbacks.onPartialResult(result.tokens);
    });

    recording.on('endpoint', () => {
      callbacks.onEndpoint();
    });

    recording.on('error', (error: Error) => {
      callbacks.onConnectionChange('error');
      callbacks.onError(error);
    });

    return {
      recording,
      client,
      source,
      temporaryKey: {
        ...temporaryKey,
        ws_base_url: wsBaseUrl,
      },
    };
  } catch (error) {
    callbacks.onConnectionChange('error');
    throw error;
  }
}
