import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * M5（asyncTranscribeFinalize 版）：转录/摘要必须走两阶段写盘。
 *
 * 旧实现 persistSessionTranscriptArtifacts 写**固定 key** `data/transcripts/{id}.json`，
 * 且写在终态 CAS 事务**之前**。拉 transcript / 写盘期间用户取消（finalizing→canceled）时
 * CAS count===0，但文件已经落在固定 key 上 —— 若该会话此前已有实时转录定稿在同一个 key，
 * 这一路就是直接覆盖掉终态转录；否则至少留一份没有 DB 行引用的孤儿。
 *
 * 下面每条都是**行为**断言（rollback / publish 到底有没有被调、参数是谁），不是快照，
 * 把两阶段任何一环拆掉都会红。
 */

const {
  sessionUpdateManyMock,
  sessionFindUniqueMock,
  transactionMock,
  getSonioxTranscriptMock,
  stageMock,
  publishMock,
  rollbackMock,
  settleStagedMock,
  readbackMock,
  runBackgroundLLMTasksMock,
  deductMock,
  settleMock,
  getSiteSettingsMock,
  deleteSonioxFileMock,
  deleteSonioxTranscriptionMock,
  convertMock,
  extractMock,
} = vi.hoisted(() => ({
  sessionUpdateManyMock: vi.fn(),
  sessionFindUniqueMock: vi.fn(),
  transactionMock: vi.fn(),
  getSonioxTranscriptMock: vi.fn(),
  stageMock: vi.fn(),
  publishMock: vi.fn(),
  rollbackMock: vi.fn(),
  settleStagedMock: vi.fn(),
  readbackMock: vi.fn(),
  runBackgroundLLMTasksMock: vi.fn(),
  deductMock: vi.fn(),
  settleMock: vi.fn(),
  getSiteSettingsMock: vi.fn(),
  deleteSonioxFileMock: vi.fn(),
  deleteSonioxTranscriptionMock: vi.fn(),
  convertMock: vi.fn(),
  extractMock: vi.fn(),
}));

vi.mock('@/lib/prisma', () => ({
  prisma: {
    session: { updateMany: sessionUpdateManyMock, findUnique: sessionFindUniqueMock },
    $transaction: (...a: unknown[]) => transactionMock(...a),
  },
}));
vi.mock('@/lib/soniox/asyncFile', () => ({
  getSonioxTranscript: getSonioxTranscriptMock,
  deleteSonioxFile: deleteSonioxFileMock,
  deleteSonioxTranscription: deleteSonioxTranscriptionMock,
}));
vi.mock('@/lib/soniox/asyncTranscriptConverter', () => ({
  convertAsyncTokensToSegments: convertMock,
  extractTranslationsByTokens: extractMock,
}));
vi.mock('@/lib/sessionPersistence', () => ({
  stageSessionTranscriptArtifacts: stageMock,
  // 收尾改成 stage → 事务内 settle → 提交后一次性 complete；抛错时 readback 判定是否已提交。
  settleStagedArtifactsInTransaction: settleStagedMock,
  completeStagedArtifactPublishes: publishMock,
  readbackStagedArtifactPublication: readbackMock,
  rollbackStagedArtifact: rollbackMock,
}));
vi.mock('@/lib/sessionFinalization', () => ({ runBackgroundLLMTasks: runBackgroundLLMTasksMock }));
vi.mock('@/lib/quota', () => ({
  deductTranscriptionMinutes: deductMock,
  settleAsyncReservation: settleMock,
}));
vi.mock('@/lib/siteSettings', () => ({ getSiteSettings: getSiteSettingsMock }));

import { finalizeAsyncTranscription } from '@/lib/audio/asyncTranscribeFinalize';
import type { SonioxRuntimeConfig } from '@/lib/soniox/env';

const CONFIG = {} as SonioxRuntimeConfig;

// 版本化引用（`{id}-{stamp}.json`）—— 与固定 key `{id}.json` 刻意不同名，正是 M5 的修法。
const STAGED_TRANSCRIPT = {
  category: 'transcripts',
  reference: 'local:transcripts/s1-ver1.json',
  localReference: 'local:transcripts/s1-ver1.json',
  storage: 'local',
};
const STAGED_SUMMARY = {
  category: 'summaries',
  reference: 'local:summaries/s1-ver1.json',
  localReference: 'local:summaries/s1-ver1.json',
  storage: 'local',
};

const makeSession = () =>
  ({
    id: 's1',
    userId: 'u1',
    sonioxFileId: 'file-1',
    sonioxTranscriptionId: 'tx-1',
    titleAutoGenerated: false,
    targetLang: 'zh',
    durationMs: 600_000,
    recordingPath: '/rec/s1',
    title: 'T',
    courseName: 'C',
    createdAt: new Date('2026-07-01T00:00:00.000Z'),
    folderIds: [],
  }) as Parameters<typeof finalizeAsyncTranscription>[0];

beforeEach(() => {
  vi.clearAllMocks();
  getSonioxTranscriptMock.mockResolvedValue({ tokens: [{ text: 'a' }] });
  convertMock.mockReturnValue([{ id: 'seg1' }]);
  extractMock.mockReturnValue([]);
  stageMock.mockResolvedValue({ transcript: STAGED_TRANSCRIPT, summary: STAGED_SUMMARY });
  publishMock.mockResolvedValue([
    { path: STAGED_TRANSCRIPT.reference, storage: 'local' },
    { path: STAGED_SUMMARY.reference, storage: 'local' },
  ]);
  rollbackMock.mockResolvedValue(undefined);
  settleStagedMock.mockImplementation(async (_tx: unknown, staged: unknown[]) =>
    staged.map((item) => ({ staged: item, settled: {} }))
  );
  // 默认：抛错路径上确证「没提交过」，可以放心回滚临时对象。
  readbackMock.mockResolvedValue({ outcome: 'not_committed', publications: [] });
  getSiteSettingsMock.mockResolvedValue({ async_upload_billing_multiplier: 0.8 });
  deductMock.mockResolvedValue(undefined);
  settleMock.mockResolvedValue(0);
  deleteSonioxFileMock.mockResolvedValue(true);
  deleteSonioxTranscriptionMock.mockResolvedValue(true);
  sessionFindUniqueMock.mockResolvedValue({ asyncTranscribeStatus: 'canceled' });
  sessionUpdateManyMock.mockResolvedValue({ count: 1 });
  transactionMock.mockImplementation(async (cb: (tx: unknown) => Promise<unknown>) =>
    cb({ session: { updateMany: sessionUpdateManyMock } })
  );
});

describe('M5：转录/摘要两阶段写盘', () => {
  it('CAS 成功：写进 DB 的是版本化引用（不是固定 key），且两个 artifact 都 publish、都不回滚', async () => {
    sessionUpdateManyMock
      .mockResolvedValueOnce({ count: 1 }) // claim
      .mockResolvedValueOnce({ count: 1 }); // 终态 CAS

    const result = await finalizeAsyncTranscription(makeSession(), CONFIG, {
      allowClaimFrom: ['transcribing'],
    });

    expect(result).toMatchObject({
      outcome: 'completed',
      transcriptPath: STAGED_TRANSCRIPT.reference,
      summaryPath: STAGED_SUMMARY.reference,
    });
    // 终态 CAS 里落库的 path 必须就是 staged 引用。
    const casCall = sessionUpdateManyMock.mock.calls[1][0];
    expect(casCall.data).toMatchObject({
      transcriptPath: STAGED_TRANSCRIPT.reference,
      summaryPath: STAGED_SUMMARY.reference,
    });
    // 固定 key 绝不出现（那才是 M5 的病灶）。
    expect(casCall.data.transcriptPath).not.toBe('local:transcripts/s1.json');

    // 两个 artifact 一次性交给 completeStagedArtifactPublishes（提交之后才发生）。
    expect(publishMock).toHaveBeenCalledTimes(1);
    const published = (
      publishMock.mock.calls[0][1] as Array<{ staged: unknown }>
    ).map((entry) => entry.staged);
    expect(published).toEqual([STAGED_TRANSCRIPT, STAGED_SUMMARY]);
    expect(rollbackMock).not.toHaveBeenCalled();
  });

  it('★ 收尾期间被取消（CAS count===0）：两个 staged 对象都被删，绝不 publish', async () => {
    sessionUpdateManyMock
      .mockResolvedValueOnce({ count: 1 }) // claim
      .mockResolvedValueOnce({ count: 0 }); // 终态 CAS 抢不到（已 canceled）
    sessionFindUniqueMock.mockResolvedValue({ asyncTranscribeStatus: 'canceled' });

    const result = await finalizeAsyncTranscription(makeSession(), CONFIG, {
      allowClaimFrom: ['transcribing'],
    });

    expect(result).toEqual({ outcome: 'canceled_during_finalize' });
    expect(rollbackMock).toHaveBeenCalledTimes(2);
    expect(rollbackMock).toHaveBeenCalledWith(expect.anything(), STAGED_TRANSCRIPT);
    expect(rollbackMock).toHaveBeenCalledWith(expect.anything(), STAGED_SUMMARY);
    // publish 只在 CAS 成功后才允许发生。
    expect(publishMock).not.toHaveBeenCalled();
    expect(deductMock).not.toHaveBeenCalled();
  });

  it('★ 守卫失败但会话并未取消（并发方回退）：同样回滚临时对象，且不删 Soniox', async () => {
    sessionUpdateManyMock
      .mockResolvedValueOnce({ count: 1 })
      .mockResolvedValueOnce({ count: 0 });
    sessionFindUniqueMock.mockResolvedValue({ asyncTranscribeStatus: 'transcribing' });

    await finalizeAsyncTranscription(makeSession(), CONFIG, {
      allowClaimFrom: ['transcribing', 'finalizing'],
    });

    expect(rollbackMock).toHaveBeenCalledTimes(2);
    expect(publishMock).not.toHaveBeenCalled();
    // P1-19 既有不变式不能被本次改动破坏。
    expect(deleteSonioxTranscriptionMock).not.toHaveBeenCalled();
    expect(deleteSonioxFileMock).not.toHaveBeenCalled();
  });

  it('★ 事务抛错且确证未提交（回退 count===1）：回滚临时对象', async () => {
    sessionUpdateManyMock
      .mockResolvedValueOnce({ count: 1 }) // claim
      .mockResolvedValueOnce({ count: 1 }); // 回退 finalizing→transcribing 命中 ⇒ CAS 必未生效
    transactionMock.mockRejectedValueOnce(new Error('Deadlock found'));

    const result = await finalizeAsyncTranscription(makeSession(), CONFIG, {
      allowClaimFrom: ['transcribing'],
    });

    expect(result).toEqual({ outcome: 'claim_lost' });
    expect(rollbackMock).toHaveBeenCalledTimes(2);
    expect(publishMock).not.toHaveBeenCalled();
  });

  it('★ 事务抛错但其实已提交（响应丢失，回退 count===0）：**绝不**回滚 —— DB 正指着这两个文件', async () => {
    sessionUpdateManyMock.mockResolvedValueOnce({ count: 1 }); // claim
    transactionMock.mockRejectedValueOnce(new Error('Connection lost after COMMIT'));
    // 判据不是「回退 CAS 的 count」，而是**回读**：DB 行已是 completed 且 path 正指着
    // 这两个 staged 对象 ⇒ 事务其实提交过，只是响应丢了。
    sessionFindUniqueMock.mockResolvedValue({
      asyncTranscribeStatus: 'completed',
      transcriptPath: STAGED_TRANSCRIPT.reference,
      summaryPath: STAGED_SUMMARY.reference,
    });
    readbackMock.mockResolvedValue({
      outcome: 'committed',
      publications: [
        { staged: STAGED_TRANSCRIPT, settled: {} },
        { staged: STAGED_SUMMARY, settled: {} },
      ],
    });

    const result = await finalizeAsyncTranscription(makeSession(), CONFIG, {
      allowClaimFrom: ['transcribing'],
    });

    // 这是本条的全部意义：删了就是把刚定稿的转录删掉。
    expect(rollbackMock).not.toHaveBeenCalled();
    expect(result).toMatchObject({
      transcriptPath: STAGED_TRANSCRIPT.reference,
      summaryPath: STAGED_SUMMARY.reference,
    });
  });

  it('stage 必须早于终态 CAS（保持「先写版本化对象、再由 CAS 认领」的顺序）', async () => {
    sessionUpdateManyMock
      .mockResolvedValueOnce({ count: 1 })
      .mockResolvedValueOnce({ count: 1 });

    await finalizeAsyncTranscription(makeSession(), CONFIG, {
      allowClaimFrom: ['transcribing'],
    });

    expect(stageMock.mock.invocationCallOrder[0]).toBeLessThan(
      sessionUpdateManyMock.mock.invocationCallOrder[1]
    );
    // publish 反过来必须晚于 CAS。
    expect(publishMock.mock.invocationCallOrder[0]).toBeGreaterThan(
      sessionUpdateManyMock.mock.invocationCallOrder[1]
    );
  });
});
