-- 会话自动标题修复：收尾后台的「只有默认标题才自动生成」检查还在比对早期占位串
-- （'新建讲座会话' / 'New Lecture Session'），而新建会话的默认标题早已改为「会话 {日期}」
-- 格式，导致自动标题生成自 2026-04 后对所有新录音永久跳过。
-- 改为显式标记：创建时客户端声明 titleAutoGenerated=true，用户手动改名清除，
-- 收尾按标记判定（老数据以占位日期格式正则兜底识别）。

-- AlterTable
ALTER TABLE `Session` ADD COLUMN `titleAutoGenerated` BOOLEAN NOT NULL DEFAULT false;
