/**
 * 异步上传转录的「共享收尾（finalize）」逻辑。
 *
 * 由两条路径复用，行为逐字一致，杜绝口径漂移 / 双扣：
 *   1. 前端轮询驱动：`src/app/api/sessions/[id]/async-transcribe-status/route.ts`
 *      —— 用户在线时，poll 到 Soniox completed 就地收尾。
 *   2. 回收兜底（cron）：`src/lib/billingMaintenance.ts` 的 reclaimStaleAsyncUploads
 *      —— 用户离线、前端不再 poll 时，回收路径查到 Soniox 已完成后自动收尾。
 *
 * 收尾口径（三处必须完全一致，改动即为红线）：
 *   - 拉 transcript → 转 segments → 两阶段落盘（stageSessionTranscriptArtifacts → CAS → publish）
 *   - 计费：ceil(getBillableMinutes(durationMs) × async_upload_billing_multiplier) 分钟，
 *     倍率默认 0.8、可在 admin 设置；与对账侧口径一致。
 *   - 幂等：依赖两道条件原子 updateMany —
 *       (a) claim：WHERE asyncTranscribeStatus IN allowedClaimFrom → 'finalizing'
 *           抢到（count===1）才继续，否则交给对方（前端 poll / 回收）二选一执行；
 *       (b) finalize 守卫：WHERE asyncTranscribeStatus='finalizing' → 'completed'
 *           抢不到（收尾期间被 cancel）则不扣费、不跑 LLM，仅清 Soniox 资源。
 *     故对同一 session，扣费恰好执行一次（回收 vs 前端 poll 互斥，绝不双扣）。
 *   - P5-7：(b) 与扣费/预留结算在**同一事务**里提交。计费失败即整体回滚、会话退回 transcribing
 *     重试，绝不出现「终态已落但净扣 0 且无复扣路径」。
 */
import type { Session } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { logger } from '@/lib/logger';
import type { SonioxRuntimeConfig } from '@/lib/soniox/env';
import {
  deleteSonioxFile,
  deleteSonioxTranscription,
  getSonioxTranscript,
} from '@/lib/soniox/asyncFile';
import {
  convertAsyncTokensToSegments,
  extractTranslationsByTokens,
} from '@/lib/soniox/asyncTranscriptConverter';
import {
  stageSessionTranscriptArtifacts,
  settleStagedArtifactsInTransaction,
  completeStagedArtifactPublishes,
  readbackStagedArtifactPublication,
  rollbackStagedArtifact,
} from '@/lib/sessionPersistence';
import { runBackgroundLLMTasks } from '@/lib/sessionFinalization';
import {
  deductTranscriptionMinutes,
  settleAsyncReservation,
} from '@/lib/quota';
import { getBillableMinutes } from '@/lib/billing';
import { getSiteSettings } from '@/lib/siteSettings';

/** finalize 只需要 session 的这些字段（route / reclaim 各自 select 需覆盖）。 */
export type FinalizableSession = Pick<
  Session,
  | 'id'
  | 'userId'
  | 'sonioxFileId'
  | 'sonioxTranscriptionId'
  | 'targetLang'
  | 'durationMs'
  | 'recordingPath'
  | 'title'
  | 'titleAutoGenerated'
  | 'courseName'
  | 'createdAt'
> & {
  /** 后台 LLM 任务需要 folderIds；route 从 include.folders 映射，reclaim 单独查。 */
  folderIds: string[];
};

export type FinalizeAsyncResult =
  | {
      /**
       * 抢锁失败：另一条路径已在收尾（或状态已变），调用方应读最新状态返回。
       * P5-7：「终态 CAS + 计费」事务整体失败（死锁/超时）已回退到 transcribing 时同样返回本值——
       * 对调用方的处置完全一致（读最新状态、交下一轮 poll/cron 重收尾），故不新增 outcome 变体。
       */
      outcome: 'claim_lost';
    }
  | {
      /** 收尾守卫失败：finalizing 期间会话被 cancel，未扣费、未跑 LLM，已清 Soniox 资源。 */
      outcome: 'canceled_during_finalize';
    }
  | {
      /** 收尾成功：已落盘、已按口径扣费、已触发后台 LLM、已清 Soniox 资源。 */
      outcome: 'completed';
      transcriptPath: string;
      summaryPath: string;
      segmentCount: number;
    };

/**
 * 收尾一份「Soniox 侧已 completed」的异步转录。**调用前提**：调用方已确认 Soniox job
 * 状态为 completed（本函数不再 poll Soniox 状态，只负责抢锁 + 拉 transcript + 落盘 + 扣费）。
 *
 * @param session          需收尾的会话（字段见 FinalizableSession）
 * @param sonioxConfig     Soniox 运行配置（用于拉 transcript / 清资源）
 * @param options.allowClaimFrom  claim 允许的起始状态集合。前端 poll 传 ['transcribing']；
 *   回收路径也传 ['transcribing']（僵尸态里只有 transcribing 才可能持有已完成的 Soniox 转录）。
 * @param options.onCompleted  收尾成功后的副作用钩子（如失效 API 缓存）。P5-7 起在「终态 CAS +
 *   扣费」的事务**提交之后**调用——事务可能整体回滚，提前失效缓存会对外暴露一个并不存在的终态。
 *
 * 注意：本函数**会抛出**拉 transcript / 落盘阶段的错误（含瞬时/永久之分由调用方判定），
 * 抛出前不改动 DB 状态——调用方需在 catch 里按 'finalizing' 守卫回退 transcribing 或标 failed。
 */
export async function finalizeAsyncTranscription(
  session: FinalizableSession,
  sonioxConfig: SonioxRuntimeConfig,
  options: {
    allowClaimFrom: string[];
    onCompleted?: (session: FinalizableSession) => Promise<void> | void;
  }
): Promise<FinalizeAsyncResult> {
  const transcriptionId = session.sonioxTranscriptionId;
  if (!transcriptionId) {
    // 理论不可达（调用方已确认 Soniox completed 必有 transcriptionId），保守当作抢锁失败。
    return { outcome: 'claim_lost' };
  }

  // ── 条件原子 claim：WHERE asyncTranscribeStatus IN allowClaimFrom → 'finalizing' ──
  // 只有一个并发路径（前端 poll / 回收）能抢到，其它读到 'finalizing' 直接放弃。
  const claim = await prisma.session.updateMany({
    where: {
      id: session.id,
      asyncTranscribeStatus: { in: options.allowClaimFrom },
    },
    data: { asyncTranscribeStatus: 'finalizing' },
  });

  if (claim.count !== 1) {
    return { outcome: 'claim_lost' };
  }

  const transcript = await getSonioxTranscript(sonioxConfig, transcriptionId);
  const segments = convertAsyncTokensToSegments(transcript.tokens, {
    targetLang: session.targetLang,
  });
  const translations = extractTranslationsByTokens(transcript.tokens, segments);

  const bundle = {
    segments,
    summaries: [],
    translations,
  };
  const staged = await stageSessionTranscriptArtifacts(session, bundle);

  // ── 终态 CAS + 计费：同一事务（P5-7）──
  // 完成写入必须带状态守卫（原 route U60 注释）：上面的 claim 把状态置 'finalizing'，但拉
  // transcript / 写盘期间用户仍可能取消（cancelAsyncUpload 的 setStatus 允许 finalizing→canceled）。
  // 条件 updateMany WHERE asyncTranscribeStatus='finalizing'：抢不到（已被取消）→ 不写库、不扣费。
  //
  // P5-7：**CAS 与计费必须同事务**。旧实现先单独提交终态（completed + billedAt），再另开事务扣费、
  // 且异常只 log 吞掉 → 计费一失败就净扣 0；而两个调用点的 allowClaimFrom 都不含 'completed'，落终态
  // 后再无任何复扣路径，维护循环 30 分钟后还会把残留预留一并释放。合并后任一步失败整体回滚：会话退回
  // transcribing（见下方 catch），交下一轮 poll / cron 重收尾，幂等 claim 保证仍恰好扣一次。
  //
  // 锁序（P5-7 的现实失败原因是死锁而非 DB 宕机）：init 路由是 Session FOR UPDATE → User update；
  // 旧的独立计费事务是 User update(deduct) → Session FOR UPDATE(settle)，同一 session 并发即成环。
  // 合并后本事务的第一条语句就是按主键 X 锁本 Session 行的 CAS，之后才动 User → 与 init 同为
  // Session→User，环被打断。
  let canceledDuringFinalize = false;
  let stagedPublications: Awaited<
    ReturnType<typeof settleStagedArtifactsInTransaction>
  > = [];
  try {
    const { async_upload_billing_multiplier } = await getSiteSettings();
    const billableMinutes = Math.ceil(
      getBillableMinutes(session.durationMs) * async_upload_billing_multiplier
    );
    const commit = await prisma.$transaction(async (tx) => {
      const finalized = await tx.session.updateMany({
        where: { id: session.id, asyncTranscribeStatus: 'finalizing' },
        data: {
          asyncTranscribeStatus: 'completed',
          transcriptPath: staged.transcript.reference,
          summaryPath: staged.summary.reference,
          // P1-17：**不再**在 CAS 提交里清 Soniox 引用 —— 改到确认 DELETE 成功/404 之后才清（见文末）。
          // 此前先清 ID 再 best-effort 删，删失败即永久失去重试依据、Soniox 侧文件/转录孤儿泄漏。
          status: 'COMPLETED',
          // B7：置扣费时刻，供对账按扣费周期归期（异步上传的权威扣费在同一事务里紧随其后）。
          billedAt: new Date(),
        },
      });
      if (finalized.count !== 1) {
        // 守卫抢不到：不扣费、不结算预留，事务空提交，交下方 canceled 分支处理。
        return { canceled: true as const, stagedPublications: [] };
      }

      // 异步上传转录计费（批2 + B1）：claim + 此处 CAS 共同保证每个 session 仅有一个路径进到这里且
      // 未被取消，故结算恰好执行一次（幂等无须额外锁）。按 ceil(分钟)×倍率 扣减，倍率默认 0.8、可在
      // admin 设置；与对账侧口径一致。
      //
      // B1：把入口预留（session.asyncReservedMinutes，已计入 used）「转」为实扣——deduct 实际 +
      // release 预留 + 清预留列。used 净变化 = 实扣，且不残留预留。
      if (billableMinutes > 0) {
        // P5-5：带 sessionId → 同事务写 Session.billedMinutes 台账，对账据此算 expected。
        await deductTranscriptionMinutes(session.userId, billableMinutes, tx, {
          sessionId: session.id,
          source: 'async_upload_finalize',
          referenceId: session.id,
        });
      }
      // settleAsyncReservation 用 FOR UPDATE 读**当前**列并原子释放。deduct 内部 ensureQuotaWindow 若
      // 刚触发月度重置会顺带清列 → 此时 settle 读到 0、不重复释放，杜绝跨周期把已被重置隐式清除的预留
      // 再减一次（审查 R1）。并发多路径经 settle 也仅释放一次。
      await settleAsyncReservation(session.id, tx);
      const publications = await settleStagedArtifactsInTransaction(tx, [
        staged.transcript,
        staged.summary,
      ]);
      return { canceled: false as const, stagedPublications: publications };
    });
    canceledDuringFinalize = commit.canceled;
    stagedPublications = commit.stagedPublications;
  } catch (billingErr) {
    // P5-7：CAS+计费整体回滚（最现实的是死锁 / 事务超时）。此刻会话仍是 'finalizing'——退回
    // transcribing，让下一次前端 poll（allowClaimFrom=['transcribing']）或 cron 回收重新收尾。
    // 带 WHERE 守卫：若事务其实已提交、只是响应丢失，状态已是 completed → 0 行、绝不回退终态。
    // 产物已落盘但未写库，重收尾会重新拉取/覆盖，幂等。
    logger.error(
      { err: billingErr, sessionId: session.id },
      'async upload finalize+billing tx failed; rolled back to transcribing for retry'
    );
    try {
      const owner = await prisma.session.findUnique({
        where: { id: session.id },
        select: {
          asyncTranscribeStatus: true,
          transcriptPath: true,
          summaryPath: true,
        },
      });
      const readback = await readbackStagedArtifactPublication(
        [staged.transcript, staged.summary],
        [owner?.transcriptPath, owner?.summaryPath]
      );
      if (
        owner?.asyncTranscribeStatus === 'completed' &&
        readback.outcome === 'committed'
      ) {
        // COMMIT succeeded and only its ACK was lost. Continue the normal
        // post-commit cleanup path; rolling back here would delete live data.
        stagedPublications = readback.publications;
      } else if (readback.outcome === 'not_committed') {
        await prisma.session
          .updateMany({
            where: { id: session.id, asyncTranscribeStatus: 'finalizing' },
            data: { asyncTranscribeStatus: 'transcribing' },
          })
          .catch(() => undefined);
        await Promise.all([
          rollbackStagedArtifact(session, staged.transcript).catch(
            () => undefined
          ),
          rollbackStagedArtifact(session, staged.summary).catch(
            () => undefined
          ),
        ]);
        return { outcome: 'claim_lost' };
      } else {
        logger.error(
          { sessionId: session.id },
          'async finalize publication outcome unknown; preserving staged artifacts'
        );
        return { outcome: 'claim_lost' };
      }
    } catch (readbackError) {
      logger.error(
        { err: readbackError, sessionId: session.id },
        'async finalize publication readback failed; preserving staged artifacts'
      );
      return { outcome: 'claim_lost' };
    }
  }

  if (canceledDuringFinalize) {
    await Promise.all([
      rollbackStagedArtifact(session, staged.transcript).catch(() => undefined),
      rollbackStagedArtifact(session, staged.summary).catch(() => undefined),
    ]);
    // 收尾守卫抢不到（finalizing 期间状态已变）。P1-19：**只有确认会话确实被取消（canceled）**才删
    // Soniox 资源——否则可能是并发 finalizer 的失败回退把状态改回 transcribing（转录仍需要），此时删
    // 外部资源会让后续 salvage getSoniox 404、会话永久卡死（回归红线）。非 canceled → 保留资源交对方/重试。
    const fresh = await prisma.session.findUnique({
      where: { id: session.id },
      select: { asyncTranscribeStatus: true },
    });
    if (fresh?.asyncTranscribeStatus === 'canceled') {
      // 确认取消：先删 transcription 再删 file（P1-17），确认删除才清 DB 外部 ID。
      const txDeleted = await deleteSonioxTranscription(sonioxConfig, transcriptionId).catch(
        () => false
      );
      const fileDeleted = session.sonioxFileId
        ? await deleteSonioxFile(sonioxConfig, session.sonioxFileId).catch(() => false)
        : true;
      if (txDeleted || fileDeleted) {
        await prisma.session
          .updateMany({
            where: { id: session.id },
            data: {
              ...(txDeleted ? { sonioxTranscriptionId: null } : {}),
              ...(fileDeleted ? { sonioxFileId: null } : {}),
            },
          })
          .catch(() => undefined);
      }
    }
    return { outcome: 'canceled_during_finalize' };
  }

  const [transcriptResult, summaryResult] =
    await completeStagedArtifactPublishes(session, stagedPublications);
  if (!transcriptResult || !summaryResult) {
    throw new Error('async transcript artifact publication was incomplete');
  }

  // 终态 + 计费已一并提交之后的副作用（route：失效 sessions API 缓存）。P5-7 之前它排在计费之前，
  // 现在计费与终态同事务提交，缓存失效必须等提交成功——否则事务回滚后缓存却已按「已完成」失效。
  if (options.onCompleted) {
    await options.onCompleted(session);
  }

  // fire-and-forget：runBackgroundLLMTasks 自带 try/catch，不阻塞响应
  void runBackgroundLLMTasks({
    sessionId: session.id,
    userId: session.userId,
    transcriptPath: staged.transcript.reference,
    summaryPath: staged.summary.reference,
    recordingPath: session.recordingPath,
    title: session.title,
    titleAutoGenerated: session.titleAutoGenerated,
    courseName: session.courseName ?? '',
    durationMs: session.durationMs,
    createdAt: session.createdAt,
    targetLang: session.targetLang || 'zh',
    folderIds: session.folderIds,
    bundle,
  });

  // 删 Soniox 上的资源（P1-17：先删 transcription 再删 file；确认删除成功/404 才清 DB 外部 ID，
  // 删失败保留 ID 交 cron reclaimOrphanSonioxResources 兜底重试，绝不永久孤儿）。幂等、失败不抛。
  const txDeleted = await deleteSonioxTranscription(sonioxConfig, transcriptionId).catch(
    () => false
  );
  const fileDeleted = session.sonioxFileId
    ? await deleteSonioxFile(sonioxConfig, session.sonioxFileId).catch(() => false)
    : true;
  if (txDeleted || fileDeleted) {
    await prisma.session
      .updateMany({
        where: { id: session.id },
        data: {
          ...(txDeleted ? { sonioxTranscriptionId: null } : {}),
          ...(fileDeleted ? { sonioxFileId: null } : {}),
        },
      })
      .catch(() => undefined);
  }

  return {
    outcome: 'completed',
    transcriptPath: staged.transcript.reference,
    summaryPath: staged.summary.reference,
    segmentCount: segments.length,
  };
}
