import { describe, expect, it } from 'vitest';
import { isAutoGeneratedSessionTitle } from '@/lib/sessionTitle';

// 收尾后台「标题仍是自动占位才生成」判定。
// 回归背景：默认标题早已换成「会话 {日期}」格式，而旧判定硬编码比对
// '新建讲座会话'/'New Lecture Session'，自动标题对新录音全部失效（2026-04 起）。

describe('isAutoGeneratedSessionTitle', () => {
  it('显式标记为真时恒判定占位（新数据真源）', () => {
    expect(isAutoGeneratedSessionTitle('随便什么标题', true)).toBe(true);
  });

  it('兜底识别当前自动日期占位（zh）', () => {
    expect(isAutoGeneratedSessionTitle('会话 7月12日 15:58', false)).toBe(true);
    expect(isAutoGeneratedSessionTitle('会话 11月3日 9:05', null)).toBe(true);
  });

  it('兜底识别当前自动日期占位（en，含 12/24 小时制变体）', () => {
    expect(isAutoGeneratedSessionTitle('Session Jul 12, 03:58 PM', false)).toBe(true);
    expect(isAutoGeneratedSessionTitle('Session Jul 12, 15:58', false)).toBe(true);
  });

  it('兜底识别历史占位（两代默认串 + API 兜底值）', () => {
    expect(isAutoGeneratedSessionTitle('新建讲座会话', false)).toBe(true);
    expect(isAutoGeneratedSessionTitle('New Lecture Session', false)).toBe(true);
    expect(isAutoGeneratedSessionTitle('Untitled Session', false)).toBe(true);
  });

  it('用户起的名字绝不判定为占位（含以「会话」开头但非日期格式的）', () => {
    expect(isAutoGeneratedSessionTitle('高等数学 第三讲', false)).toBe(false);
    expect(isAutoGeneratedSessionTitle('会话 张三的课', false)).toBe(false);
    expect(isAutoGeneratedSessionTitle('Session notes for Monday', false)).toBe(false);
    expect(isAutoGeneratedSessionTitle('lecture-fat · 5月16日 21:03', false)).toBe(false);
  });
});
