import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  userFindUnique: vi.fn(),
  loadBundle: vi.fn(),
  extractTranscriptText: vi.fn(),
  resolveUserFeatureFlags: vi.fn(),
  resolveUserSummaryModels: vi.fn(),
  resolveSummaryModel: vi.fn(),
  generateOrReuseSessionReport: vi.fn(),
  trackJob: vi.fn(),
  invalidateSessionsApiCache: vi.fn(),
  invalidateFoldersApiCache: vi.fn(),
  queryRaw: vi.fn(),
}));

vi.mock('@/lib/prisma', () => ({
  prisma: {
    user: { findUnique: mocks.userFindUnique },
    session: { update: vi.fn() },
    $queryRaw: mocks.queryRaw,
  },
}));
vi.mock('@/lib/sessionPersistence', () => ({
  stageSessionAudioArtifact: vi.fn(),
  finalizeStagedArtifactPublish: vi.fn(),
  rollbackStagedArtifact: vi.fn(),
  loadSessionTranscriptBundle: mocks.loadBundle,
  extractTranscriptText: mocks.extractTranscriptText,
}));
vi.mock('@/lib/userRoles', () => ({
  resolveUserFeatureFlags: mocks.resolveUserFeatureFlags,
  resolveUserSummaryModels: mocks.resolveUserSummaryModels,
}));
vi.mock('@/lib/llm/summaryModel', () => ({
  resolveSummaryModel: mocks.resolveSummaryModel,
}));
vi.mock('@/lib/llm/gateway', () => ({ callLLM: vi.fn() }));
vi.mock('@/lib/llm/reportManager', () => ({
  generateSessionTitle: vi.fn(),
}));
vi.mock('@/lib/llm/reportGenerationService', () => ({
  generateOrReuseSessionReport: mocks.generateOrReuseSessionReport,
}));
vi.mock('@/lib/llm/folderKeywords', () => ({
  extractAndAccumulateKeywords: vi.fn(),
}));
vi.mock('@/lib/sessionTitle', () => ({
  isAutoGeneratedSessionTitle: vi.fn(() => false),
}));
vi.mock('@/lib/jobQueue', () => ({
  trackJob: mocks.trackJob,
  JOB_TYPE: {
    KEYWORD_EXTRACTION: 'keyword_extraction',
    TITLE_GENERATION: 'title_generation',
  },
}));
vi.mock('@/lib/apiResponseCache', () => ({
  invalidateSessionsApiCache: mocks.invalidateSessionsApiCache,
  invalidateFoldersApiCache: mocks.invalidateFoldersApiCache,
}));
vi.mock('@/lib/logger', () => ({
  logger: {
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    child: vi.fn(() => ({ info: vi.fn(), warn: vi.fn(), error: vi.fn() })),
  },
  serializeError: (error: unknown) => error,
}));

import { runBackgroundLLMTasks } from '@/lib/sessionFinalization';

describe('runBackgroundLLMTasks report single-flight integration', () => {
  beforeEach(() => {
    vi.resetAllMocks();
    mocks.userFindUnique.mockResolvedValue({ role: 'PRO', customGroupId: null });
    mocks.resolveUserFeatureFlags.mockResolvedValue({ allowFinalSummary: true });
    mocks.resolveUserSummaryModels.mockResolvedValue({
      finalSummaryModelId: 'summary-model-1',
    });
    mocks.resolveSummaryModel.mockResolvedValue({
      routing: { modelId: 'summary-model-1' },
      provider: {
        dbModelId: 'summary-model-1',
        contextWindow: 32_768,
        maxTokens: 4096,
      },
    });
    mocks.loadBundle.mockResolvedValue({
      segments: [{ id: 'segment-1', text: 'lecture' }],
      summaries: [],
    });
    mocks.extractTranscriptText.mockReturnValue('lecture '.repeat(100));
    mocks.generateOrReuseSessionReport.mockResolvedValue({
      status: 'in_progress',
      sourceHash: 'a'.repeat(64),
      plan: {
        providerCalls: 2,
        reservedTokens: 10_000,
        chunkCount: 0,
        usesMapReduce: false,
      },
    });
    mocks.invalidateSessionsApiCache.mockResolvedValue(undefined);
    mocks.invalidateFoldersApiCache.mockResolvedValue(undefined);
    mocks.queryRaw.mockResolvedValue([]);
  });

  it('finalize 后台与手动 POST 共用 report service，不再另包一层 report trackJob', async () => {
    await runBackgroundLLMTasks({
      sessionId: 'session-1',
      userId: 'user-1',
      transcriptPath: 'transcript.json',
      summaryPath: 'summary.json',
      recordingPath: null,
      title: 'Custom title',
      titleAutoGenerated: false,
      courseName: 'Security',
      durationMs: 60_000,
      createdAt: new Date('2026-08-20T00:00:00.000Z'),
      targetLang: 'en',
      folderIds: [],
      bundle: null,
    });

    expect(mocks.generateOrReuseSessionReport).toHaveBeenCalledWith(
      expect.objectContaining({
        session: expect.objectContaining({
          id: 'session-1',
          userId: 'user-1',
          transcriptPath: 'transcript.json',
        }),
        transcript: 'lecture '.repeat(100),
        contextWindow: 32_768,
        maxOutputTokens: 4096,
        modelKey: 'summary-model-1',
        triggeredBy: 'system',
      })
    );
    expect(mocks.trackJob).not.toHaveBeenCalled();
    expect(mocks.invalidateSessionsApiCache).toHaveBeenCalledWith('user-1');
  });
});
