import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * M5 + L20：收尾产物的两阶段提交必须覆盖**全部三类**产物（录音 / 转录 / 摘要），
 * 且回滚必须覆盖**全部未提交路径**（CAS 输了 + 事务自身抛错）。
 *
 * M5（旧洞）：P0-6 的 stage→CAS→publish/rollback 只给了录音，转录/摘要仍走
 * persistSessionTranscriptArtifacts 写**固定 key** `{id}.json`，且写在 CAS 事务之前。
 * finalizer A 因大文件 ffmpeg 超过 FINALIZE_LOCK_STALE_MS(15min) 被 B 接管时：B 先提交自己的
 * bundle，A 随后 count===0 走 lockLost —— 旧代码只 rollback stagedAudio，A 覆盖掉的那份固定 key
 * 转录/摘要**原地不动**，而 DB 指向的正是这个 path ⇒ 最终存储的转录 ≠ 提交时审计的转录。
 *
 * L20（旧洞）：`$transaction` 自身抛错（死锁/锁等待超时/连接断开）时 CAS 从未生效，
 * 但 stage 出的版本化文件（本地 + 可能的 Cloudreve 远程副本）已经落盘 —— 旧代码只有 lockLost
 * 分支回滚，这条路径把它们漏成无主孤儿（无任何 DB 行引用，删会话时也扫不到）。
 *
 * 反向契约（同样要锁住）：CAS **提交之后**再抛错，绝不能回滚 —— 那会删掉刚定稿的录音/转录。
 */

const {
  sessionFindUniqueMock,
  sessionUpdateManyMock,
  transactionMock,
  txSessionUpdateManyMock,
  txSessionFindUniqueMock,
  deductMock,
  sumGrantActualMsMock,
  settleGrantsMock,
  transcriptDurationMock,
  serverDurationMock,
  mergeDraftMock,
  stageAudioMock,
  stageTranscriptMock,
  publishMock,
  rollbackMock,
  settleStagedMock,
  readbackMock,
  loadDraftMock,
} = vi.hoisted(() => ({
  sessionFindUniqueMock: vi.fn(),
  sessionUpdateManyMock: vi.fn(),
  transactionMock: vi.fn(),
  txSessionUpdateManyMock: vi.fn(),
  txSessionFindUniqueMock: vi.fn(),
  deductMock: vi.fn(),
  sumGrantActualMsMock: vi.fn(),
  settleGrantsMock: vi.fn(),
  transcriptDurationMock: vi.fn(),
  serverDurationMock: vi.fn(),
  mergeDraftMock: vi.fn(),
  stageAudioMock: vi.fn(),
  stageTranscriptMock: vi.fn(),
  publishMock: vi.fn(),
  rollbackMock: vi.fn(),
  settleStagedMock: vi.fn(),
  readbackMock: vi.fn(),
  loadDraftMock: vi.fn(),
}));

vi.mock('@/lib/prisma', () => ({
  prisma: {
    session: {
      findUnique: sessionFindUniqueMock,
      updateMany: sessionUpdateManyMock,
      update: vi.fn().mockResolvedValue(undefined),
    },
    user: { findUnique: vi.fn().mockResolvedValue(null) },
    $transaction: (...a: unknown[]) => transactionMock(...a),
  },
}));
vi.mock('@/lib/security', () => ({ assertOwnership: vi.fn() }));
vi.mock('@/lib/recordingDraftPersistence', () => ({
  mergeRecordingDraftChunks: mergeDraftMock,
  deleteRecordingDraft: vi.fn().mockResolvedValue(undefined),
  sealRecordingDraft: vi.fn().mockResolvedValue(undefined),
  unsealRecordingDraft: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/transcriptDraftPersistence', () => ({
  loadTranscriptDraft: loadDraftMock,
  deleteTranscriptDraft: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/sessionPersistence', () => ({
  stageSessionAudioArtifact: stageAudioMock,
  stageSessionTranscriptArtifacts: stageTranscriptMock,
  // 收尾改成 stage → 事务内 settle → 提交后 complete；失败/抢输走 readback + rollback。
  settleStagedArtifactsInTransaction: settleStagedMock,
  completeStagedArtifactPublishes: publishMock,
  readbackStagedArtifactPublication: readbackMock,
  rollbackStagedArtifact: rollbackMock,
  extractTranscriptText: vi.fn(() => ''),
  loadSessionTranscriptBundle: vi.fn().mockResolvedValue(null),
  persistSessionReport: vi.fn().mockResolvedValue({ path: 'rp/1.json' }),
}));
vi.mock('@/lib/audio/recordingDuration', () => ({
  resolveServerRecordingDurationMs: serverDurationMock,
  resolveTranscriptDurationMs: transcriptDurationMock,
  normalizeRecordedAudioDuration: vi.fn().mockResolvedValue(Buffer.alloc(4)),
  measureAuthoritativeRecordingDurationMsFromBuffer: vi.fn().mockResolvedValue(1000),
  RECORDING_DURATION_LIMIT_GRACE_MS: 60_000,
  RecordingDurationMeasurementError: class RecordingDurationMeasurementError extends Error {},
}));
vi.mock('@/lib/billing', () => ({
  clampSessionDurationMs: (ms: number) => ms,
  getBillableMinutes: (ms: number) => (ms > 0 ? Math.ceil(ms / 60_000) : 0),
  getMaxSessionDurationMs: () => null,
}));
vi.mock('@/lib/quota', () => ({ deductTranscriptionMinutes: deductMock }));
vi.mock('@/lib/email/quotaAlert', () => ({
  maybeSendTranscriptionQuotaAlert: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/soniox/streamGrant', () => ({
  settleStreamGrants: settleGrantsMock,
  sumSessionGrantActualMs: sumGrantActualMsMock,
}));
vi.mock('@/lib/userRoles', () => ({
  resolveUserFeatureFlags: vi.fn().mockResolvedValue({ allowFinalSummary: false }),
  resolveUserSummaryModels: vi.fn().mockResolvedValue({ finalSummaryModelId: null }),
}));
vi.mock('@/lib/llm/gateway', () => ({ callLLM: vi.fn() }));
vi.mock('@/lib/llm/summaryModel', () => ({
  resolveSummaryModel: vi.fn().mockResolvedValue({ routing: {}, provider: null }),
}));
vi.mock('@/lib/llm/folderKeywords', () => ({
  extractAndAccumulateKeywords: vi.fn(),
}));
vi.mock('@/lib/llm/reportManager', () => ({
  generateSessionReport: vi.fn(),
  generateSessionTitle: vi.fn(),
}));
vi.mock('@/lib/sessionTitle', () => ({
  isAutoGeneratedSessionTitle: vi.fn(() => false),
}));
vi.mock('@/lib/auditLog', () => ({ logSystemEvent: vi.fn() }));
vi.mock('@/lib/jobQueue', () => ({
  trackJob: vi.fn().mockResolvedValue(undefined),
  JOB_TYPE: {},
}));
vi.mock('@/lib/audio/enhanceProcessor', () => ({
  maybeEnqueueAudioEnhanceForSession: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/apiResponseCache', () => ({
  invalidateFoldersApiCache: vi.fn().mockResolvedValue(undefined),
  invalidateSessionsApiCache: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/logger', () => {
  const noop = vi.fn();
  const child = { info: noop, warn: noop, error: noop, debug: noop, child: () => child };
  return {
    logger: { ...child, child: () => child },
    serializeError: (e: unknown) => e,
  };
});

import { finalizeSession } from '@/lib/sessionFinalization';

/** settle 在事务内把每个 staged 换成可发布句柄；readback 默认判定「没提交过」。 */
function settledStagedReset() {
  settleStagedMock
    .mockReset()
    .mockImplementation(async (_tx: unknown, staged: unknown[]) =>
      staged.map((item) => ({ staged: item, settled: {} }))
    );
  readbackMock.mockReset().mockResolvedValue({ outcome: 'not_committed', publications: [] });
}

/** 收尾前：录音/转录/摘要三个 path 都还是空 → 三类产物本次都要 stage。 */
const SESSION = {
  id: 'sess-1',
  userId: 'u1',
  status: 'FINALIZING',
  title: 't',
  titleAutoGenerated: false,
  courseName: '',
  targetLang: 'zh',
  recordingPath: null,
  transcriptPath: null,
  summaryPath: null,
  durationMs: 0,
  serverStartedAt: new Date('2026-08-22T10:00:00.000Z'),
  serverPausedAt: null,
  createdAt: new Date('2026-08-22T10:00:00.000Z'),
  folders: [],
  user: { role: 'FREE', email: 'u1@example.com' },
};

/** stage 出来的**版本化**引用（注意：绝不是固定 key `sess-1.json`）。 */
const STAGED_AUDIO = {
  category: 'recordings',
  reference: 'local:recordings/sess-1-k1a2b3c4.webm',
  localReference: 'local:recordings/sess-1-k1a2b3c4.webm',
  storage: 'local',
  previousReference: null,
};
const STAGED_TRANSCRIPT = {
  category: 'transcripts',
  reference: 'local:transcripts/sess-1-k1deadbe.json',
  localReference: 'local:transcripts/sess-1-k1deadbe.json',
  storage: 'local',
  previousReference: null,
};
const STAGED_SUMMARY = {
  category: 'summaries',
  reference: 'local:summaries/sess-1-k1cafe00.json',
  localReference: 'local:summaries/sess-1-k1cafe00.json',
  storage: 'local',
  previousReference: null,
};

/** rollbackStagedArtifact 实际被回滚掉的 reference 列表（顺序无关，用集合比对）。 */
const rolledBack = () =>
  rollbackMock.mock.calls
    .map((c) => (c[1] as { reference: string }).reference)
    .sort();

beforeEach(() => {
  sessionFindUniqueMock.mockReset().mockResolvedValue(SESSION);
  sessionUpdateManyMock.mockReset().mockResolvedValue({ count: 1 }); // 抢到 finalize 锁
  txSessionUpdateManyMock.mockReset().mockResolvedValue({ count: 1 }); // CAS 赢
  txSessionFindUniqueMock
    .mockReset()
    .mockResolvedValue({ ...SESSION, status: 'COMPLETED' });
  transactionMock.mockReset().mockImplementation(
    async (cb: (tx: unknown) => Promise<unknown>) =>
      cb({
        session: {
          updateMany: txSessionUpdateManyMock,
          findUnique: txSessionFindUniqueMock,
        },
      })
  );
  deductMock.mockReset().mockResolvedValue({ role: 'FREE' });
  settleGrantsMock
    .mockReset()
    .mockResolvedValue({ settledCount: 0, releasedMinutes: 0, actualMsTotal: 0 });
  sumGrantActualMsMock.mockReset().mockResolvedValue(0);
  transcriptDurationMock.mockReset().mockReturnValue(60_000);
  serverDurationMock.mockReset().mockReturnValue(60_000);
  mergeDraftMock.mockReset().mockResolvedValue({
    buffer: Buffer.alloc(4),
    manifest: { mimeType: 'audio/webm' },
    hasGap: false,
  });
  loadDraftMock.mockReset().mockResolvedValue({
    // SEC-009：收尾时 transcript bundle 要过严格 schema，只有 {id} 会被 400 拒收。
    segments: [
      {
        id: 's1',
        sessionIndex: 0,
        speaker: 'Speaker 1',
        language: 'zh',
        text: '一段转录',
        globalStartMs: 0,
        globalEndMs: 1000,
        startMs: 0,
        endMs: 1000,
        isFinal: true,
        confidence: 1,
        timestamp: '00:00:00',
      },
    ],
    summaries: [],
    translations: {},
  });
  stageAudioMock.mockReset().mockResolvedValue(STAGED_AUDIO);
  stageTranscriptMock
    .mockReset()
    .mockResolvedValue({ transcript: STAGED_TRANSCRIPT, summary: STAGED_SUMMARY });
  publishMock
    .mockReset()
    .mockResolvedValue([
      { path: 'published', storage: 'local' },
      { path: 'published', storage: 'local' },
    ]);
  rollbackMock.mockReset().mockResolvedValue(undefined);
  settledStagedReset();
});

describe('finalizeSession — M5：转录/摘要走 stage → CAS → publish 两阶段', () => {
  it('▶ CAS 赢：写库的是版本化引用（非固定 key {id}.json），提交后三类产物全部 publish', async () => {
    const res = await finalizeSession({ sessionId: 'sess-1', actor: null });

    expect(stageTranscriptMock).toHaveBeenCalledTimes(1);
    // 写进 CAS 事务的 path 必须是 stage 出来的版本化引用 —— 旧实现写的是被并发 finalizer
    // 覆盖过的固定 key。
    expect(txSessionUpdateManyMock.mock.calls[0][0].data).toMatchObject({
      status: 'COMPLETED',
      recordingPath: STAGED_AUDIO.reference,
      transcriptPath: STAGED_TRANSCRIPT.reference,
      summaryPath: STAGED_SUMMARY.reference,
    });
    expect(res.transcriptPath).toBe(STAGED_TRANSCRIPT.reference);
    expect(res.summaryPath).toBe(STAGED_SUMMARY.reference);

    // 提交之后才发布，且三类一次性交给 completeStagedArtifactPublishes
    // （转录/摘要无 previousReference，publish 是纯语义调用）。
    expect(publishMock).toHaveBeenCalledTimes(1);
    const published = (
      publishMock.mock.calls[0][1] as Array<{ staged: { reference: string } }>
    )
      .map((entry) => entry.staged.reference)
      .sort();
    expect(published).toEqual(
      [
        STAGED_AUDIO.reference,
        STAGED_TRANSCRIPT.reference,
        STAGED_SUMMARY.reference,
      ].sort()
    );
    expect(rollbackMock).not.toHaveBeenCalled();
  });

  it('▶ M5 lockLost（锁被接管者先提交）：转录与摘要**也**被回滚，不只回滚录音', async () => {
    txSessionUpdateManyMock.mockResolvedValueOnce({ count: 0 }); // 锁已被 B 接管
    sessionFindUniqueMock.mockResolvedValue(SESSION);

    const res = await finalizeSession({ sessionId: 'sess-1', actor: null });

    expect(res.alreadyCompleted).toBe(true);
    // ▶ 旧实现这里只有 recordings 一条 —— transcripts/summaries 留在固定 key 上覆盖了 B 的产物。
    expect(rolledBack()).toEqual(
      [
        STAGED_AUDIO.reference,
        STAGED_TRANSCRIPT.reference,
        STAGED_SUMMARY.reference,
      ].sort()
    );
    // CAS 没生效 → 一个都不许 publish。
    expect(publishMock).not.toHaveBeenCalled();
  });
});

describe('finalizeSession — L20：事务抛错路径也要清 staged', () => {
  it('▶ $transaction 抛错（死锁/超时）：三类 staged 全部回滚，错误照常上抛', async () => {
    transactionMock.mockRejectedValueOnce(
      Object.assign(new Error('Deadlock found when trying to get lock'), {
        code: 'P2034',
      })
    );

    await expect(
      finalizeSession({ sessionId: 'sess-1', actor: null })
    ).rejects.toThrow(/Deadlock/);

    // ▶ 旧实现：lockLost 有 rollback，事务抛错这条路径一个都不删 → 版本化文件成无主孤儿。
    expect(rolledBack()).toEqual(
      [
        STAGED_AUDIO.reference,
        STAGED_TRANSCRIPT.reference,
        STAGED_SUMMARY.reference,
      ].sort()
    );
    expect(publishMock).not.toHaveBeenCalled();
  });

  it('▶ 反向契约：CAS 已提交之后再抛错，绝不回滚（否则删掉刚定稿的产物）', async () => {
    // CAS 赢（count=1）但事务内回读 updated 为 null → 提交之后访问 updatedSession.title 抛 TypeError。
    txSessionUpdateManyMock.mockResolvedValueOnce({ count: 1 });
    txSessionFindUniqueMock.mockResolvedValueOnce(null);

    await expect(
      finalizeSession({ sessionId: 'sess-1', actor: null })
    ).rejects.toBeInstanceOf(TypeError);

    expect(rollbackMock).not.toHaveBeenCalled();
    // 提交后的发布照常发生（发布在抛错点之前）。
    expect(publishMock).toHaveBeenCalled();
  });
});
