import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * P5-6：Soniox 实测串流量（sumSessionGrantActualMs）必须是**所有** finalize 路径的时长下限。
 * 旧实现只在 auto-reclaim 时取、用户主动收尾硬编码 0 —— 而「改装客户端直连串流、收尾时上报 0
 * 时长」走的正是用户路径；截断后的值又写回 Session.durationMs，对账 expected 按同一个值重算
 * → drift 恒 0，账面上完全看不见。
 *
 * 顺带锁住 P5-5 契约：扣费带 { sessionId }，同事务追加进 Session.billedMinutes 不可变台账。
 */

const {
  sessionFindUniqueMock,
  sessionUpdateManyMock,
  transactionMock,
  txSessionUpdateManyMock,
  txSessionFindUniqueMock,
  deductMock,
  sumGrantActualMsMock,
  settleGrantsMock,
  transcriptDurationMock,
  serverDurationMock,
  mergeDraftMock,
  stageTranscriptMock,
  loadDraftMock,
} = vi.hoisted(() => ({
  sessionFindUniqueMock: vi.fn(),
  sessionUpdateManyMock: vi.fn(),
  transactionMock: vi.fn(),
  txSessionUpdateManyMock: vi.fn(),
  txSessionFindUniqueMock: vi.fn(),
  deductMock: vi.fn(),
  sumGrantActualMsMock: vi.fn(),
  settleGrantsMock: vi.fn(),
  transcriptDurationMock: vi.fn(),
  serverDurationMock: vi.fn(),
  mergeDraftMock: vi.fn(),
  stageTranscriptMock: vi.fn(),
  loadDraftMock: vi.fn(),
}));

vi.mock('@/lib/prisma', () => ({
  prisma: {
    session: {
      findUnique: sessionFindUniqueMock,
      updateMany: sessionUpdateManyMock,
      update: vi.fn().mockResolvedValue(undefined),
    },
    user: { findUnique: vi.fn().mockResolvedValue(null) },
    $transaction: (...a: unknown[]) => transactionMock(...a),
  },
}));
vi.mock('@/lib/security', () => ({ assertOwnership: vi.fn() }));
vi.mock('@/lib/recordingDraftPersistence', () => ({
  mergeRecordingDraftChunks: mergeDraftMock,
  deleteRecordingDraft: vi.fn().mockResolvedValue(undefined),
  sealRecordingDraft: vi.fn().mockResolvedValue(undefined),
  unsealRecordingDraft: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/transcriptDraftPersistence', () => ({
  loadTranscriptDraft: loadDraftMock,
  deleteTranscriptDraft: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/sessionPersistence', () => ({
  stageSessionAudioArtifact: vi.fn().mockResolvedValue(null),
  finalizeStagedArtifactPublish: vi.fn().mockResolvedValue(undefined),
  rollbackStagedArtifact: vi.fn().mockResolvedValue(undefined),
  stageSessionTranscriptArtifacts: stageTranscriptMock,
  extractTranscriptText: vi.fn(() => ''),
  loadSessionTranscriptBundle: vi.fn().mockResolvedValue(null),
  persistSessionReport: vi.fn().mockResolvedValue({ path: 'rp/1.json' }),
}));
vi.mock('@/lib/audio/recordingDuration', () => ({
  resolveServerRecordingDurationMs: serverDurationMock,
  resolveTranscriptDurationMs: transcriptDurationMock,
  normalizeRecordedAudioDuration: vi.fn().mockResolvedValue(Buffer.alloc(0)),
}));
// billing 是纯函数模块，复刻真实口径（clamp FREE 2h、ceil 到分钟）——它正是本条的计费口径本身。
vi.mock('@/lib/billing', () => ({
  clampSessionDurationMs: (ms: number, role: string) =>
    role === 'ADMIN' ? ms : Math.min(ms, 2 * 60 * 60_000),
  getBillableMinutes: (ms: number) => (ms > 0 ? Math.ceil(ms / 60_000) : 0),
}));
vi.mock('@/lib/quota', () => ({ deductTranscriptionMinutes: deductMock }));
vi.mock('@/lib/email/quotaAlert', () => ({
  maybeSendTranscriptionQuotaAlert: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/soniox/streamGrant', () => ({
  settleStreamGrants: settleGrantsMock,
  sumSessionGrantActualMs: sumGrantActualMsMock,
}));
vi.mock('@/lib/userRoles', () => ({
  resolveUserFeatureFlags: vi.fn().mockResolvedValue({ allowFinalSummary: false }),
  resolveUserSummaryModels: vi.fn().mockResolvedValue({ finalSummaryModelId: null }),
}));
vi.mock('@/lib/llm/gateway', () => ({ callLLM: vi.fn() }));
vi.mock('@/lib/llm/summaryModel', () => ({
  resolveSummaryModel: vi.fn().mockResolvedValue({ routing: {}, provider: null }),
}));
vi.mock('@/lib/llm/folderKeywords', () => ({
  extractAndAccumulateKeywords: vi.fn(),
}));
vi.mock('@/lib/llm/reportManager', () => ({
  generateSessionReport: vi.fn(),
  generateSessionTitle: vi.fn(),
}));
vi.mock('@/lib/sessionTitle', () => ({
  isAutoGeneratedSessionTitle: vi.fn(() => false),
}));
vi.mock('@/lib/auditLog', () => ({ logSystemEvent: vi.fn() }));
vi.mock('@/lib/jobQueue', () => ({
  trackJob: vi.fn().mockResolvedValue(undefined),
  JOB_TYPE: {},
}));
vi.mock('@/lib/audio/enhanceProcessor', () => ({
  maybeEnqueueAudioEnhanceForSession: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/apiResponseCache', () => ({
  invalidateFoldersApiCache: vi.fn().mockResolvedValue(undefined),
  invalidateSessionsApiCache: vi.fn().mockResolvedValue(undefined),
}));
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
  serializeError: (e: unknown) => e,
}));

import { finalizeSession } from '@/lib/sessionFinalization';

const SESSION = {
  id: 'sess-1',
  userId: 'u1',
  status: 'FINALIZING',
  title: 't',
  titleAutoGenerated: false,
  courseName: '',
  targetLang: 'zh',
  recordingPath: 'rec/existing.webm',
  transcriptPath: null,
  summaryPath: null,
  durationMs: 0,
  serverStartedAt: new Date('2026-07-16T10:00:00.000Z'),
  serverPausedAt: null,
  createdAt: new Date('2026-07-16T10:00:00.000Z'),
  folders: [],
  user: { role: 'FREE', email: 'u1@example.com' },
};

beforeEach(() => {
  sessionFindUniqueMock.mockReset().mockResolvedValue(SESSION);
  sessionUpdateManyMock.mockReset().mockResolvedValue({ count: 1 }); // 抢到 finalize 锁
  txSessionUpdateManyMock.mockReset().mockResolvedValue({ count: 1 });
  txSessionFindUniqueMock
    .mockReset()
    .mockResolvedValue({ ...SESSION, status: 'COMPLETED' });
  transactionMock.mockReset().mockImplementation(
    async (cb: (tx: unknown) => Promise<unknown>) =>
      cb({
        session: {
          updateMany: txSessionUpdateManyMock,
          findUnique: txSessionFindUniqueMock,
        },
      })
  );
  deductMock.mockReset().mockResolvedValue({ role: 'FREE' });
  settleGrantsMock
    .mockReset()
    .mockResolvedValue({ settledCount: 1, releasedMinutes: 15, actualMsTotal: 0 });
  sumGrantActualMsMock.mockReset().mockResolvedValue(0);
  // 「改装客户端只串流不回传内容」的形态：转录 0 段、服务端墙钟也不可信（无内容佐证）。
  transcriptDurationMock.mockReset().mockReturnValue(0);
  serverDurationMock.mockReset().mockReturnValue(0);
  mergeDraftMock.mockReset().mockResolvedValue(null);
  loadDraftMock.mockReset().mockResolvedValue(null);
  // M5：转录/摘要改走两阶段 stage —— 返回的是版本化引用，CAS 成功后才 publish。
  stageTranscriptMock.mockReset().mockResolvedValue({
    transcript: { category: 'transcripts', reference: 'local:transcripts/sess-1-a1.json', localReference: 'local:transcripts/sess-1-a1.json', storage: 'local', previousReference: null },
    summary: { category: 'summaries', reference: 'local:summaries/sess-1-a1.json', localReference: 'local:summaries/sess-1-a1.json', storage: 'local', previousReference: null },
  });
});

describe('finalizeSession — P5-6：Soniox 实测量恒为时长下限', () => {
  it('用户主动收尾 + 转录/墙钟皆 0 + 实测串流 15 分钟 → 按 15 分钟扣费（旧实现扣 0）', async () => {
    sumGrantActualMsMock.mockResolvedValueOnce(15 * 60_000);

    await finalizeSession({ sessionId: 'sess-1', actor: null });

    expect(sumGrantActualMsMock).toHaveBeenCalledWith('sess-1');
    expect(deductMock).toHaveBeenCalledWith(
      'u1',
      15,
      expect.anything(),
      expect.objectContaining({ sessionId: 'sess-1' })
    );
    // 回写的 durationMs 也含实测量 —— 对账 expected 按同一个值重算，口径才自洽
    expect(txSessionUpdateManyMock.mock.calls[0][0].data).toMatchObject({
      status: 'COMPLETED',
      durationMs: 15 * 60_000,
    });
  });

  it('unload 路径（finalizeSource=unload）同样取实测量', async () => {
    sumGrantActualMsMock.mockResolvedValueOnce(7 * 60_000);

    await finalizeSession({
      sessionId: 'sess-1',
      actor: null,
      finalizeSource: 'unload',
    });

    expect(deductMock).toHaveBeenCalledWith(
      'u1',
      7,
      expect.anything(),
      expect.objectContaining({ sessionId: 'sess-1' })
    );
  });

  it('内容口径本来就更长 → 取较大者，诚实用户口径不变', async () => {
    transcriptDurationMock.mockReturnValue(40 * 60_000);
    sumGrantActualMsMock.mockResolvedValueOnce(15 * 60_000);

    await finalizeSession({ sessionId: 'sess-1', actor: null });

    expect(deductMock).toHaveBeenCalledWith(
      'u1',
      40,
      expect.anything(),
      expect.anything()
    );
  });

  it('无 grant 实测（未串流 / usage-logs 未回填）→ 退回内容口径，不凭空加钱', async () => {
    transcriptDurationMock.mockReturnValue(3 * 60_000);
    sumGrantActualMsMock.mockResolvedValueOnce(0);

    await finalizeSession({ sessionId: 'sess-1', actor: null });

    expect(deductMock).toHaveBeenCalledWith(
      'u1',
      3,
      expect.anything(),
      expect.anything()
    );
  });

  it('sumSessionGrantActualMs 抛错 → 吞掉按 0 计，收尾不被计费查询拖垮', async () => {
    transcriptDurationMock.mockReturnValue(2 * 60_000);
    sumGrantActualMsMock.mockRejectedValueOnce(new Error('db down'));

    const res = await finalizeSession({ sessionId: 'sess-1', actor: null });

    expect(res.success).toBe(true);
    expect(deductMock).toHaveBeenCalledWith(
      'u1',
      2,
      expect.anything(),
      expect.anything()
    );
  });
});
